# Generated by Django 3.1.5 on 2021-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('descripción', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='User')),
                ('coment', models.CharField(max_length=300, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Dietas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('descripción', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('descripción', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('ingredientes', models.CharField(max_length=300, verbose_name='Ingredientes')),
                ('preparación', models.CharField(max_length=400, verbose_name='Preparación')),
            ],
        ),
    ]
