# Generated by Django 3.1.5 on 2021-01-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0002_alimentos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietas',
            name='imagen',
            field=models.CharField(max_length=100, null=True, verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='dietas',
            name='links',
            field=models.CharField(max_length=200, null=True, verbose_name='links'),
        ),
    ]
