# Generated by Django 3.1.5 on 2021-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0003_auto_20210121_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='imagen',
            field=models.CharField(max_length=100, null=True, verbose_name='imagen'),
        ),
    ]
